server {
    listen 80;

    root /var/www/html;
    index index.php index.html;

    # Redireciona raiz para a loja
    location = / {
        return 302 /loja/index.php;
    }

    location /loja {
        try_files $uri $uri/ /loja/index.php?$query_string;
    }

    location /admin {
        try_files $uri $uri/ /admin/index.php?$query_string;
    }

    # Servir imagens e arquivos estáticos diretamente
    location ~* \.(png|jpg|jpeg|gif|ico|css|js)$ {
        try_files $uri =404;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
    }
}
